# dotfiles
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

autoload -Uz add-zsh-hook

_show_command_timestamp() {
  print -P "%F{8}%D{%H:%M:%S}%f"
}

add-zsh-hook preexec _show_command_timestamp

# Aliases
alias gits="git s"
alias work="cd ~/work"

# Path
export PATH=$HOME/bin:$HOME/go/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Editor
export EDITOR='nvim'
