# dotfiles
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

autoload -Uz add-zsh-hook

_cmd_entered_at=""

_record_command_time() {
  _cmd_entered_at="$(date +%H:%M)"
}

add-zsh-hook preexec _record_command_time
RPROMPT='${_cmd_entered_at}'

# Aliases
alias gits="git s"
alias work="cd ~/work"

# Path
export PATH=$HOME/bin:$HOME/go/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Editor
export EDITOR='nvim'
